name: iOS Build and Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      # Checkout the repository
      - name: Checkout Source
        uses: actions/checkout@v4

      # Set up Xcode 16
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"

      # List available runtimes for debugging
      - name: List Available Runtimes
        run: xcrun simctl list runtimes

      # Clean and reset simulators
      - name: Clean Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all
          xcrun simctl delete unavailable

      # Create and Boot iPhone 15 Simulator
      - name: Create and Boot iPhone 15 Simulator
        run: |
          xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-0
          xcrun simctl boot "iPhone 15"

      # Resolve Swift Package Dependencies
      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies

      # Run tests
      - name: Run Tests
        run: |
          xcodebuild test \
            -workspace "CommerceLab.xcworkspace" \
            -scheme "CommerceLab" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" \
            -derivedDataPath DerivedData
