name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest  # Use the latest macOS runner for Xcode 16 compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16"

      - name: Resolve Swift Package Dependencies
        run: |
          # Resolve SPM dependencies to generate the workspace
          xcodebuild -resolvePackageDependencies -scheme CommerceLab

      - name: Build
        env:
          scheme: CommerceLab
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          xcodebuild build-for-testing -scheme "$scheme" -destination "platform=iOS Simulator,name=$device"

      - name: Test
        env:
          scheme: CommerceLab
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=iOS Simulator,name=$device"
