name: iOS Build and Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      # Checkout the repository
      - name: Checkout Source
        uses: actions/checkout@v4

      # Set up Xcode 16
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0" # Specify Xcode 16

      # Clean up and reset simulators
      - name: Clean Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all
          xcrun simctl delete unavailable

      # Boot the required simulator
      - name: Boot Simulator
        run: |
          xcrun simctl boot "iPhone 14"

      # Resolve Swift Package Dependencies
      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies

      # Run tests
      - name: Run Tests
        run: |
          xcodebuild test \
            -workspace "CommerceLab.xcworkspace" \
            -scheme "CommerceLab" \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" \
            -derivedDataPath DerivedData
