name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest  # Use the latest macOS runner for Xcode 16 compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16"

      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Clean Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all
          xcrun simctl delete unavailable

      - name: Boot Simulator
        run: |
          xcrun simctl boot "iPhone 14" || true

      - name: Run Tests
        run: |
          xcodebuild test \
            -workspace "CommerceLab.xcworkspace" \
            -scheme "CommerceLab" \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" \
            -derivedDataPath DerivedData \
            -maximum-test-execution-time 1200
