name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15  # Use macos-13 for Xcode 15 compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json 2>/dev/null | tr -d "\n")
          if [[ -z "$scheme_list" ]]; then
            echo "Error: Unable to list schemes. Ensure your project file format is compatible."
            exit 1
          fi
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        env:
          scheme: CommerceLab
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild build-for-testing -scheme "$scheme" -workspace "CommerceLab.xcworkspace" -destination "platform=iOS Simulator,name=$device"

      - name: Test
        env:
          scheme: CommerceLab
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild test-without-building -scheme "$scheme" -workspace "CommerceLab.xcworkspace" -destination "platform=iOS Simulator,name=$device"
